/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import configuration.PackageConfiguration;
import configuration.SystemMessages;
import constant.PlaneConstants;
import controller.DatabaseController;
import controller.PackageController;
import model.Airport;
import model.Flight;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author Dalescio
 */
public class RegistroPacote extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPacote
     */
    public RegistroPacote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TipoRegistro = new javax.swing.JComboBox<>();
        CategoriaRegistro = new javax.swing.JComboBox<>();
        DestinoRegistro = new javax.swing.JComboBox<>();
        NomeResponsavel = new javax.swing.JTextField();
        PesoRegistro = new javax.swing.JTextField();
        KgRegistro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        PoraoRegistro = new javax.swing.JComboBox<>();
        AeronaveRegistro = new javax.swing.JComboBox<>();
        VoltarRegistro = new javax.swing.JButton();
        RegistroRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registrar Pacote");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Dados do pacote");

        TipoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(PackageConfiguration.PACKAGE_TYPES));
        TipoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoRegistroActionPerformed(evt);
            }
        });

        CategoriaRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(PackageConfiguration.PACKAGE_CATEGORIES));
        CategoriaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaRegistroActionPerformed(evt);
            }
        });

        ArrayList<String> airportCodes = new ArrayList<String>();
        for(Airport airport : DatabaseController.getAirports()) {
            airportCodes.add(airport.getCode());
        }
        DestinoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(airportCodes.toArray(new String[0])));
        DestinoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinoRegistroActionPerformed(evt);
            }
        });

        NomeResponsavel.setText("Nome do responsável");
        NomeResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeResponsavelActionPerformed(evt);
            }
        });

        PesoRegistro.setText("Peso");
        PesoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoRegistroActionPerformed(evt);
            }
        });

        KgRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(PackageConfiguration.PACKAGE_WEIGTH_FORMATES));
        KgRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KgRegistroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Dados do transporte");

        PoraoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(PlaneConstants.PLANE_CARGO_QUANTITY));
        PoraoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoraoRegistroActionPerformed(evt);
            }
        });

        ArrayList<String> fligthLabels = new ArrayList<String>();
        for (Flight fligth : DatabaseController.getFlights()) {
            fligthLabels.add(String.format("%s - %s - %s > %s", fligth.getId(), fligth.getPlaneCallsign(), fligth.getArrival(), fligth.getDeparture()));
        }

        AeronaveRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(fligthLabels.toArray(new String[0])));
        AeronaveRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VooRegistroActionPerformed(evt);
            }
        });

        VoltarRegistro.setText("Voltar");
        VoltarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRegistroActionPerformed(evt);
            }
        });

        RegistroRegistro.setText("Registrar");
        RegistroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PesoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KgRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(AeronaveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(PoraoRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VoltarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(280, 280, 280)
                                    .addComponent(jLabel1)))
                            .addGap(283, 283, 283)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeResponsavel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CategoriaRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(DestinoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PortaoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VooRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
<<<<<<< HEAD
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipoRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoriaRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DestinoRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(NomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesoRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KgRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PoraoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AeronaveRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                .addGap(37, 37, 37)))
>>>>>>> df378a5ba8642d0c7023b83f219d20fae0fc7c99
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestinoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoriaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KgRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
<<<<<<< HEAD
                    .addComponent(PortaoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AeronaveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PoraoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(VooRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(RegistroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
=======
                    .addComponent(PoraoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AeronaveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGap(13, 13, 13)
                .addComponent(RegistroRegistro)
                .addContainerGap(23, Short.MAX_VALUE))
>>>>>>> df378a5ba8642d0c7023b83f219d20fae0fc7c99
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoRegistroActionPerformed

    private void CategoriaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaRegistroActionPerformed

    private void DestinoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinoRegistroActionPerformed

    private void NomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeResponsavelActionPerformed

    private void PesoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoRegistroActionPerformed

    private void KgRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KgRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KgRegistroActionPerformed

    private void PoraoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortaoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortaoRegistroActionPerformed

    private void VooRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AeronaveRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AeronaveRegistroActionPerformed

    private void RegistroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroRegistroActionPerformed
        int weight = -1;
        try {
            weight = Integer.parseInt(PesoRegistro.getText());
        } catch (Exception e) {
            System.out.println(e);
        }
        if(weight >= 1) {
            String planeCallsign = AeronaveRegistro.getSelectedItem().toString().split("-")[1].replaceAll("\\s", "");
            if (PackageController.addPackage(TipoRegistro.getSelectedItem().toString(), CategoriaRegistro.getSelectedItem().toString(), NomeResponsavel.getText(), weight, KgRegistro.getSelectedItem().toString(), planeCallsign, PoraoRegistro.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(null, SystemMessages.SUCCESS_PACKAGE_CREATION);
            } else {
                JOptionPane.showMessageDialog(null, SystemMessages.FAIL_PACKAGE_CREATION);
            }
        } else {
            JOptionPane.showMessageDialog(null, SystemMessages.WRONG_INT_VALUE_MESSAGE);
        }
    }//GEN-LAST:event_RegistroRegistroActionPerformed

    private void VoltarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRegistroActionPerformed
        setVisible(false);
        dispose();
        Menu.main();
    }//GEN-LAST:event_VoltarRegistroActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPacote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AeronaveRegistro;
    private javax.swing.JComboBox<String> CategoriaRegistro;
    private javax.swing.JComboBox<String> DestinoRegistro;
    private javax.swing.JComboBox<String> KgRegistro;
    private javax.swing.JTextField NomeResponsavel;
    private javax.swing.JTextField PesoRegistro;
    private javax.swing.JComboBox<String> PoraoRegistro;
    private javax.swing.JButton RegistroRegistro;
    private javax.swing.JComboBox<String> TipoRegistro;
    private javax.swing.JButton VoltarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
